### ISSUE TITLE
Issue 1: User can search for a stock by its symbol

### ISSUE THREAD

**Issue by yadanur** [yadanur/ajax-project#1]
# Functionality
User can search for a stock by its symbol

## ✅  Task List

- [x] Create static landing page
- [x] Create landing page HTML content
- [x] Style landing page to match wireframe
- [ ] Create stock price page
- [ ] Create stock price page HTML content with dummy data
- [ ] Style stock price page to match wireframe
- [ ] Add stock price search functionality
- [ ] Clicking "Show Stock Price" button gets stock price data from the API
- [ ] Successfully getting stock price data from the API causes the stock price page to show with the correct data
